package crossbrowserTest;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import io.github.bonigarcia.wdm.WebDriverManager;
import utility.ReadDataConfig;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LOGNLOGOUTTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	
	  
//	  WebDriverManager.chromedriver().setup();
//    driver = new ChromeDriver();
    
	  WebDriverManager.chromedriver().setup();
	    driver = new ChromeDriver();
    
    
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void lOGNLOGOUT() throws Exception {
	  
	  
	  //url into config file
	  
	 // System.out.println("url");
	 ReadDataConfig appurl = new ReadDataConfig(); 
	  
	 driver.get(appurl.getApp()); 
   // driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
    
    Thread.sleep(4000);
    
    driver.manage().window().setSize(new Dimension(1936, 923));
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("Admin");
    driver.findElement(By.name("password")).sendKeys("admin123");
    driver.findElement(By.cssSelector(".oxd-button")).click();
    
    Thread.sleep(4000);
    
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".oxd-text--h6"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector(".oxd-text--h6")).getText(), is("Dashboard"));
    driver.findElement(By.cssSelector(".bi-caret-down-fill")).click();
    
    
    Thread.sleep(4000);
    
    driver.findElement(By.linkText("Logout")).click();
    
    Thread.sleep(4000);
    
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".orangehrm-login-forgot-header"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector(".orangehrm-login-forgot-header")).getText(), is("Forgot your Password?"));
  }
}
